apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nnag6ir8z-java-springboot
  janus-idp.io/tekton: nnag6ir8z-java-springboot
  backstage.io/kubernetes-id: nnag6ir8z-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nnag6ir8z-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
